config/routes.rb
Rails.application.routes.draw do
  get 'home/about', to: 'homes#about'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'homes#top'

  resources :blogs, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :picture, PictureUploader
  validate  :picture_size

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_path
  end
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.page(params[:page]).per(5)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(post_params)
    @blog.user_id = current_user.id
    @blog.save
    redirect_to '/blogs'
  end

  def show
    @blog = Blog.find(params[:id])
  end

  private
    def post_params #ストロングパラメータ
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'User was successfully updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :picture)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<div class="container">
  <h2>記事一覧</h2>
  <%= link_to ' 投稿', new_blog_path, class: "btn btn-primary" %>
  <ul>
  <% @blogs.each do |blog| %>
    <div class="card w-75 mb-3">
      <div class="card-body">
        <h3 class="card-title"><%= blog.title %></h3>
        <h6 class="card-subtitle mb-2 text-muted fas fa-user"><%= blog.user_id %></h6>
        <p class="card-text"><%= blog.body %></p>
        <%= link_to ' 詳細', blog_path(blog.id) %>
      </div>
    </div>
  <% end %>
  </ul>

  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="container">
<h1>記事作成</h1>
<%= form_with model: @blog, local:true do |f| %>
  <div class="mb-3">
    <label class="form-label">タイトル</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <label class="form-label">内容</label>
    <%= f.text_area :body, class: "form-control"%>
  </div>
  <%= f.submit '投稿', class: "btn btn-primary"%>
<% end %>
</div>

app/views/blogs/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>blog</h1>
        <body>
          <div><%= @blog.title %></div>
          <div><%= @blog.body %></div>
        </body>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<h1><strong>Bloggers!</strong></h1>

app/views/homes/top.html.erb
<main class="center-block">
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>Welcome to <strong>Bloggers</strong> !!</h1>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-block sign_up" href="/users/sign_up">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand text-light" href="#">Bloggers</a>
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <strong><%#= link_to current_user.username, auth_show_path %></strong>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'nav-link text-white' %>
                <%= link_to ' ホーム', user_path(current_user.id), class: ' nav-link text-white' %>
                <%= link_to '投稿一覧', blogs_path, class: ' nav-link text-white' %>
                <%= link_to 'ユーザ一覧', users_path, class: ' nav-link text-white' %>
              <% else %>
                <%= link_to ' ログイン', new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
                <%= link_to ' ホーム', root_path, class: 'fas fa-home nav-link text-white' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="m-2 text-danger">
    <%= @user.errors.count %>errors have occurred.
    <% @user.errors.full_messages.each do |message| %>
  </div>
    <li class="m-2 text-danger"><%= message %></li>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class=class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>User info</h1>
        <%= form_with model:@user, local:true do |f| %>
        <div class="field mb-3">
          <label for="inputName">Name</label></br>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name", class: "form-control"%></br>
        </div>
        <div class="field mb-3">
          <label for="inputIntroduction">Introduction</label></br>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction", class: "form-control"%></br>
        </div>
        <span class="user_picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
        <div class="form-group"></br>
          <input type="submit" name="commit" value="Update User" class="btn btn-lg btn-primary btn-bloc" data-disable-with="Update User"></br>
        </div>

        <% end %>
        
    </div>
  </div>
</div>
<main>
  

app/views/users/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <%= link_to '編集', edit_user_path(current_user.id) %>
          <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h6 class="border-bottom pb-2 mb-0">ユーザ一覧</h6>
                        <% @users.each do |user| %>
              <tr>
                <td></td>
              </tr>
            <div class="d-flex text-muted pt-3">
              
              <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

              <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                <div class="d-flex justify-content-between">
                  <strong class="text-gray-dark"><%= user.name %></strong>
                  <%= link_to 'Show', user_path(user.id) %>
                </div>
                <span class="d-block"><%= user.email %></span>
              </div>
            </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
      <h5 class="border-bottom pb-2 mb-0">ユーザ情報</h5>
      <div class="d-flex text-muted pt-3">
        <div class="pb-3 mb-0 lh-sm w-100">
          <%= image_tag @user.picture.url if @user.picture? %>
          <div class="d-flex justify-content-between">
            <strong class="text-gray-dark"><%= @user.name %></strong>
          </div>
          <span class="d-block"><%= @user.email %></span>
        </div>
      </div>
          <h5 class="border-bottom pb-2 mb-0">自己紹介</h5>
          <div class="d-flex text-muted pt-3">
        <div class="pb-3 mb-0 lh-sm w-100">
          <div class="d-flex justify-content-between">
          </div>
          <span class="d-block"><%= @user.introduction %></span>
        </div>
      </div>
    </div>
  </div>
</main>